name: sphae
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.12
  - snakemake>=9.5.1
  - pyyaml>=6.0
  - click>=8.1.3
  - metasnek>=0.0.4
  - snaketool-utils>=0.0.4
  - attrmap>=0.0.7
  - biopython>=1.8.1
