name: spae
channels:
  - conda-forge
  - anaconda
  - bioconda
dependencies:
  - python>=3.9
  - snakemake>=7.14.0
  - pyyaml>=6.0
  - click>=8.1.3
  - mamba<1.4.2
  - metasnek>=0.0.4
  - snaketool-utils>=0.0.4
  - attrmap>=0.0.7
  - biopython>=1.8.1
