resources:
  med:
    cpu: 8
    mem: 16000
    time: 04:00:00
trimnami:
  args:
    fastqc: false
    host: null
    log: example-nano/logs/trimnami.log
    minimap: sr
    output: example-nano/
    reads: example-nano/temp/samples.reads.tsv
    subsample: null
  qc:
    compression: 1
    fastp: --qualified_quality_phred 15 --length_required 90 --cut_tail --cut_tail_window_size
      25 --cut_tail_mean_quality 15 --dedup --dup_calc_accuracy 4 --trim_poly_x --detect_adapter_for_pe
    hostRemoveFlagstat: -f 4 -F 3584
    minimapIndex: -I 8G
    nanopore:
      filtlong: --min_length 1000 --keep_percent 95
    prinseq: -min_len 60 -min_qual_mean 25 -ns_max_n 1 -derep 1 -out_format 0 -trim_tail_left
      5 -trim_tail_right 5 -ns_max_n 5 -trim_qual_type min -trim_qual_left 30 -trim_qual_right
      30 -trim_qual_window 10
